Type script develop
alexandrlonski/client pull request #4
Opened 2021-12-17 16:45 UTC by alexandrlonski

![ts](https://user-images.githubusercontent.com/57103844/146578640-d960c40b-92ce-4205-b7b7-4a622cf4dba2.PNG)

Rewrite the project to TypeScript

Ticket: https://trello.com/c/kgjuCCjj

2021-12-19 21:51 UTC, yavorovsky requested changes

2021-12-19 21:51 UTC, yavorovsky commented on public/index.html
> +      style="
Don't use inline styles!!!

2021-12-19 21:51 UTC, yavorovsky commented on src/App.tsx
> +import { useDispatch } from "react-redux";
Not critical, but rather have order "library imports" then -> "custom utils" -> "custom components" -> "scss/css"

2021-12-19 21:51 UTC, yavorovsky commented on src/App.tsx
> +    check()
What's "check" means? Use more meaningful names!

2021-12-19 21:51 UTC, yavorovsky commented on src/App.tsx
> +        dispatch(changeUserRole(data.role));
Redux async action maybe?

2021-12-19 21:51 UTC, yavorovsky commented on src/components/AboutCinema/AboutCinema.tsx
> +          src="http://visit-petersburg.ru/media/uploads/tourobject/198842/198842_cover.jpeg.1050x700_q95_crop_upscale.jpg"
Wtf? Why the url is used as inline? Use a separate constant for this

2021-12-19 21:51 UTC, yavorovsky commented on src/components/AppRouter/AppRouter.tsx
> +        {isAuth && !(role === "ADMIN")
"ADMIN" should be a constant.

2021-12-19 21:51 UTC, yavorovsky commented on src/components/FilmDesc/FilmDesc.tsx
> +          onClick={() => (isAuth ? navigate(BUY_TICKET) : navigate("/login"))}>
"/login" should be containing in constant f.e. authPaths.login

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Header/Header.tsx
> +              <div onClick={() => logout()} className="link button">
Why? Please get acquainted with useCallback

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Header/Header.tsx
> +  const logout = (): void => {
why?

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Header/Header.tsx
> +              <NavLink to={role === "ADMIN" ? ADMIN_ROUTE : BASKET_ROUTE}>
constant

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Header/Header.tsx
> +                      ? "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG859lMWMgKWIw_iHz-7K5k77ZvxXkDCWLdw&usqp=CAU"
constants

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Modal/Modal.tsx
> +        {isAuth ? (
why?

2021-12-19 21:51 UTC, yavorovsky commented on src/components/Modal/Modal.tsx
> +          {isAuth ? "Do you really want to leave?" : text}
I don't understand why this modal does different work. Do you use this as a logout modal by default and as a generic for another case? It's weird. Please use logout modal as a different modal component and you won't need any "isAuth" stuff. You may not show the modal if the user isn't logged in

2021-12-19 21:51 UTC, yavorovsky commented on src/http/userApi.ts
> +  role = "USER"
constant. Imagine you changed the Role name. How are you going to fix it? By using replace for each place use used the string? Sounds sucks

2021-12-19 21:51 UTC, yavorovsky commented on src/pages/BuyTicket.tsx
> +  const { filmId } = useSelector((state: RootState) => state.filmId);
const film = films.find(film => film.id);

2021-12-19 21:51 UTC, yavorovsky commented on src/pages/BuyTicket.tsx
> +          .filter((film) => film.id === filmId)
You're not going to render more than 1 item. The filter and map are redundant.

2021-12-19 21:51 UTC, yavorovsky commented on src/pages/LoginP.tsx
> +  return <Login />;
Looks weird. Are you sure you need the decorator?

2021-12-19 21:51 UTC, yavorovsky commented on src/pages/Register.tsx
> +  return <Registeration />;
The same here. Don't you think the Registration gonna render the same? If you're going to extend it. OK. but if you're not. Please remove the wrapper component

2021-12-19 21:51 UTC, yavorovsky commented on src/redux/action-creators/modal.ts
> +});
think over the logic of showing modal. Looks strange..

2021-12-19 21:51 UTC, yavorovsky commented on src/redux/reducer/userReducer.ts
> +      return { ...state, role: "USER", isAuth: false };
constant

2021-12-20 11:42 UTC, alexandrlonski commented on public/index.html
> +      style="
+

2021-12-20 11:43 UTC, alexandrlonski commented on src/App.tsx
> +import { useDispatch } from "react-redux";
+

2021-12-20 11:44 UTC, alexandrlonski commented on src/App.tsx
> +    check()
+

2021-12-20 11:44 UTC, alexandrlonski commented on src/App.tsx
> +        dispatch(changeUserRole(data.role));
+

2021-12-20 11:44 UTC, alexandrlonski commented on src/components/AboutCinema/AboutCinema.tsx
> +          src="http://visit-petersburg.ru/media/uploads/tourobject/198842/198842_cover.jpeg.1050x700_q95_crop_upscale.jpg"
+

2021-12-20 11:44 UTC, alexandrlonski commented on src/components/AppRouter/AppRouter.tsx
> +        {isAuth && !(role === "ADMIN")
+

2021-12-20 11:44 UTC, alexandrlonski commented on src/components/FilmDesc/FilmDesc.tsx
> +          onClick={() => (isAuth ? navigate(BUY_TICKET) : navigate("/login"))}>
+

2021-12-20 11:45 UTC, alexandrlonski commented on src/components/Header/Header.tsx
> +              <div onClick={() => logout()} className="link button">
+

2021-12-20 11:51 UTC, alexandrlonski commented on src/components/Header/Header.tsx
> +              <NavLink to={role === "ADMIN" ? ADMIN_ROUTE : BASKET_ROUTE}>
+

2021-12-20 11:51 UTC, alexandrlonski commented on src/components/Header/Header.tsx
> +                      ? "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG859lMWMgKWIw_iHz-7K5k77ZvxXkDCWLdw&usqp=CAU"
+

2021-12-20 11:52 UTC, alexandrlonski commented on src/http/userApi.ts
> +  role = "USER"
+

2021-12-20 11:52 UTC, alexandrlonski commented on src/pages/BuyTicket.tsx
> +  const { filmId } = useSelector((state: RootState) => state.filmId);
+

2021-12-20 11:52 UTC, alexandrlonski commented on src/pages/BuyTicket.tsx
> +          .filter((film) => film.id === filmId)
+

2021-12-20 11:52 UTC, alexandrlonski commented on src/pages/LoginP.tsx
> +  return <Login />;
+

2021-12-20 11:52 UTC, alexandrlonski commented on src/pages/Register.tsx
> +  return <Registeration />;
+

2021-12-20 11:53 UTC, alexandrlonski commented on src/redux/reducer/userReducer.ts
> +      return { ...state, role: "USER", isAuth: false };
+

2021-12-27 08:27 UTC, merged